### ISSUE TITLE
wg-components April 2021 Office Hours

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/wg-components#78]
**Meeting date/time (UTC)**
04/20/2021 - 6PM UTC, 11AM PST

**Instructions for joining the meeting**
Join [https://meet.google.com/spd-oowj-ndo](https://meet.google.com/spd-oowj-ndo), and you will be let in

**Agenda**
GitHub Projects
Project updates

**Comment by jaygray0919** [comment]
Thank you for the call. We will recap the list/template issue with live code and link to this issue.

**Comment by jaygray0919** [comment]
@micajuine-ho Rather than opening another issue, i'll include two working examples from previously posted issues.

v4-40 illustrates a single hierarchical JSON `list`, a single `template` and CSS to maintain inline paragraph control:
  [https://afdsi.com/samouri-amp/v4-40/](https://afdsi.com/samouri-amp/v4-40/)

v6-40 illustrates two `list`s, two `template`s and CSS that fails to maintain inline paragraph control:
[https://afdsi.com/samouri-amp/v6-40/](https://afdsi.com/samouri-amp/v6-40/)

either `list` or `template` injects a line break that prohibits the ability to have atomic lists (i.e. definition of a single word in multiple natural languages) and use more than one atomic list in a paragraph.

said another way: we cannot implement a tooltip from a library of words - each coded in a list - in a paragraph.

our request is to replace the list/template block level control with inline control.

**Comment by alanorozco** [comment]
@jaygray0919 The templates in the `<amp-list>`s shown  are very large, could you please:

- isolate a single paragraph with a single tooltip, so I can read the code 
- show a screenshot pointing at the linebreak you don't want
- show an example/screenshot of what you want
